In [ ]:
from pathlib import Path

import pandas as pd

from utils.general import get_project_root

In [6]:
dir_path_solutions = Path(f"{get_project_root()}/solutions")

In [8]:
# After the loop finishes:
df = pd.read_csv(f"{dir_path_solutions}/eval/run_eval_final.csv")

In [10]:
df

    problem_id version_tag  target_answer  successful_solutions           mae
0     BWOR-022         v00      -3.170086                     1  7.298556e-14
1     BWOR-063         v00      16.000000                     0  1.000000e+01
2     BWOR-049         v00    1490.000000                     1  0.000000e+00
3     BWOR-055         v00    1500.000000                     1  0.000000e+00
4     BWOR-069         v00     500.000000                     1  0.000000e+00
..         ...         ...            ...                   ...           ...
241   BWOR-080         v13  937151.785700                     1  1.524371e-11
242   BWOR-025         v13      81.000000                     0  1.000000e+01
243   BWOR-035         v13      20.548322                     0  1.000000e+01
244   BWOR-019         v13       9.260000                     1  0.000000e+00
245   BWOR-072         v13       1.200000                     0  1.000000e+01

[246 rows x 5 columns]

In [23]:
df["nummerical_answer"] = 1 
df.loc[df["target_answer"].isnull(), "nummerical_answer"] = 0
df.loc[df["target_answer"].isna(), "nummerical_answer"] = 0
df["valid_mae_answer"] = 1 
df.loc[df["mae"]>0.5, "valid_mae_answer"] = 0
df["valid_mae"] = df["mae"].values 
df.loc[df["valid_mae_answer"]==0, "valid_mae"] = 0

In [ ]:
df_g = df[["version_tag", "successful_solutions", "nummerical_answer", "valid_mae_answer", "mae", "valid_mae"]].groupby(by="version_tag").sum()
df_g["mae"] = df_g["mae"]/df_g["nummerical_answer"]
df_g["valid_mae"] = df_g["valid_mae"]/df_g["valid_mae_answer"]

In [25]:
df_g

,successful_solutions,nummerical_answer,valid_mae_answer,mae,valid_mae
version_tag,,,,,
v0,62,80,60,2.750288,0.000383
v00,54,80,53,3.625386,0.000583
v13,59,80,57,3.126227,0.001722